package org.broadinstitute.sting.alignment.bwa;

import org.broadinstitute.sting.gatk.walkers.ReadWalker;
import org.broadinstitute.sting.utils.BaseUtils;
import org.broadinstitute.sting.utils.StingException;
import org.broadinstitute.sting.utils.cmdLine.Argument;
import org.broadinstitute.sting.alignment.Alignment;
import net.sf.samtools.SAMRecord;

/**
 * Validates alignments against existing reads.
 *
 * @author mhanna
 * @version 0.1
 */
public class AlignmentValidationWalker extends ReadWalker<Integer,Integer> {
    @Argument(fullName="BWTPrefix",shortName="BWT",doc="Index files generated by bwa index -d bwtsw",required=false)
    String prefix = "/Users/mhanna/reference/Ecoli/Escherichia_coli_K12_MG1655.fasta";

    private BWACAligner aligner = null;


    @Override
    public void initialize() {
        aligner = new BWACAligner(prefix + ".ann",
                                  prefix + ".amb",
                                  prefix + ".pac",
                                  prefix + ".bwt",
                                  prefix + ".sa",
                                  prefix + ".rbwt",
                                  prefix + ".rsa");        
    }

    public Integer reduceInit() { return 0; }

    @Override
    public Integer map(char[] ref, SAMRecord read) {
        byte[] bases = read.getReadBases();
        if(read.getReadNegativeStrandFlag()) bases = BaseUtils.simpleReverseComplement(bases);

        boolean matches = true;
        Alignment[] alignments = aligner.getAlignments(bases);

        if(alignments.length == 0 && !read.getReadUnmappedFlag())
            matches = false;
        else {
            for(Alignment alignment: alignments) {
                matches = (alignment.getAlignmentStart() == read.getAlignmentStart());
                matches &= (alignment.isNegativeStrand() == read.getReadNegativeStrandFlag());
                matches &= (alignment.getCigar().equals(read.getCigar()));
                matches &= (alignment.getMappingQuality() == read.getMappingQuality());
                if(matches) break;
            }
        }

        if(!matches)
            throw new StingException(String.format("Read %s mismatches!", read.getReadName()));

        return 1;
    }

    public Integer reduce(Integer value, Integer sum) {
        return value + sum;
    }

    @Override
    public void onTraversalDone(Integer result) {
        aligner.close();
        super.onTraversalDone(result);
    }

}
