/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sandbox_JNIHaplotypeDataHolderClass */

#ifndef _Included_Sandbox_JNIHaplotypeDataHolderClass
#define _Included_Sandbox_JNIHaplotypeDataHolderClass
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
