/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sandbox_JNIReadDataHolderClass */

#ifndef _Included_Sandbox_JNIReadDataHolderClass
#define _Included_Sandbox_JNIReadDataHolderClass
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
