/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM */

#ifndef _Included_org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM
#define _Included_org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM
#ifdef __cplusplus
extern "C" {
#endif
#undef org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_TRISTATE_CORRECTION
#define org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_TRISTATE_CORRECTION 3.0
#undef org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_matchToMatch
#define org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_matchToMatch 0L
#undef org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_indelToMatch
#define org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_indelToMatch 1L
#undef org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_matchToInsertion
#define org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_matchToInsertion 2L
#undef org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_insertionToInsertion
#define org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_insertionToInsertion 3L
#undef org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_matchToDeletion
#define org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_matchToDeletion 4L
#undef org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_deletionToDeletion
#define org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_deletionToDeletion 5L
#undef org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_sse42Mask
#define org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_sse42Mask 1LL
#undef org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_avxMask
#define org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_avxMask 2LL
/*
 * Class:     org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM
 * Method:    jniGetMachineType
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_jniGetMachineType
  (JNIEnv *, jobject);

/*
 * Class:     org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM
 * Method:    jniClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_jniClose
  (JNIEnv *, jobject);

/*
 * Class:     org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM
 * Method:    jniGlobalInit
 * Signature: (Ljava/lang/Class;Ljava/lang/Class;J)V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_jniGlobalInit
  (JNIEnv *, jobject, jclass, jclass, jlong);

/*
 * Class:     org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM
 * Method:    jniInitializeHaplotypes
 * Signature: (I[Lorg/broadinstitute/sting/utils/pairhmm/VectorLoglessPairHMM/JNIHaplotypeDataHolderClass;)V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_jniInitializeHaplotypes
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM
 * Method:    jniFinalizeRegion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_jniFinalizeRegion
  (JNIEnv *, jobject);

/*
 * Class:     org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM
 * Method:    jniComputeLikelihoods
 * Signature: (II[Lorg/broadinstitute/sting/utils/pairhmm/VectorLoglessPairHMM/JNIReadDataHolderClass;[Lorg/broadinstitute/sting/utils/pairhmm/VectorLoglessPairHMM/JNIHaplotypeDataHolderClass;[DI)V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_sting_utils_pairhmm_VectorLoglessPairHMM_jniComputeLikelihoods
  (JNIEnv *, jobject, jint, jint, jobjectArray, jobjectArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
